apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-2
  namespace: default
  labels:
    app: web
spec:
  containers:
    - image: nginx:latest
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: config-volume
  volumes:
    - name: config-volume
      configMap:
        name: password
        items:
          - key: pw
            path: index.html
